#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='nano'
export VISUAL='nano'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Overwrite all the previous path setup.
path=(
'/Users/sbagley/.local/bin'
'/Users/sbagley/bin'
'/opt/homebrew/bin'
'/opt/homebrew/sbin'
'/usr/local/bin'
'/usr/local/sbin'
'/usr/bin'
'/usr/sbin'
'/bin'
'/sbin'
'/Library/TeX/texbin'
'/opt/X11/bin'
'/Applications/Emacs.app/Contents/MacOS/bin'
'/Applications/LibreOffice.app/Contents/MacOS'
'/Users/sbagley/adb-fastboot/platform-tools'
)

## this can be used to add the /opt/homebrew paths (not needed, I add
## them myself in the correct place, above):
## eval "$(/opt/homebrew/bin/brew shellenv)"

## set up completion
autoload -Uz compinit
compinit

export PATH

export HOMEBREW_NO_INSTALL_CLEANUP=1
export HOMEBREW_NO_ENV_HINTS=1

## this is needed for mu4e. See
## https://github.com/moriyoshi/cyrus-sasl-xoauth2/issues/9#issuecomment-2568755701
export SASL_PATH=/opt/homebrew/opt/cyrus-sasl/lib/sasl2:/opt/homebrew/opt/cyrus-sasl-xoauth2/lib/sasl2

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
export LESS='-g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# Local Variables:
# mode: shell-script
# End:
