#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='nano'
export VISUAL='nano'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Overwrite all the previous path setup.
path=(
'/Users/sbagley/bin'
'/opt/local/bin'
'/opt/local/sbin'
'/usr/local/bin'
'/usr/local/sbin'
'/usr/bin'
'/usr/sbin'
'/bin'
'/sbin'
'/Library/TeX/texbin'
'/opt/X11/bin'
'/Applications/LibreOffice.app/Contents/MacOS'
'/Applications/Emacs.app/Contents/MacOS/bin'
'/Applications/Racket\ v7.4/bin'
'/Users/sbagley/adb-fastboot/platform-tools'
)

export PATH

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
export LESS='-g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# Local Variables:
# mode: shell-script
# End:
